package com.hanna.webservice.domain.posts;

import org.aspectj.lang.annotation.After;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import static org.assertj.core.api.Assertions.assertThat;
import java.util.List;

@SpringBootTest
@ExtendWith(SpringExtension.class)
public class PostsRepositoryTest {

    @Autowired
    PostsRepository postsRepository;


    //@After(value = "execution(* com.test.controller.TestController.*(..))")
    @AfterEach //테스트 후 수행
    public void cleanup() {
        postsRepository.deleteAll(); //삭제
    }

     /*
       * Log
         Hibernate: delete from posts where id=? ---4
     */

    @Test
    public void boardComs() {
        //given
        String title = "test title";
        String content = "test content";

     /*
       * Log
         create table posts (id bigint generated by default as identity, author varchar(255), content TEXT not null, title varchar(500) not null, primary key (id)) --1
     */
        postsRepository.save(Posts.builder() //save : posts테이블에 id값이 있다면 update, 없다면 insert
                        .title(title)
                        .content(content)
                        .author("hannakwak00@gmail.com")
                .build());
      /*
         * log
           Hibernate: insert into posts (id, author, content, title) values (default, ?, ?, ?) --2
      */
        //when
        List<Posts> postsList = postsRepository.findAll(); //findAll : posts테이블에 있는 모든 데이터 조회

      /*
         * log
           Hibernate: select p1_0.id,p1_0.author,p1_0.content,p1_0.title from posts p1_0 ---3
      */


        //then
        Posts posts = postsList.get(0);
        assertThat(posts.getTitle()).isEqualTo(title);
        assertThat(posts.getContent()).isEqualTo(content);
    }


}
